enableGlobalCache: false

enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  "@xstate/cli@*":
    peerDependencies:
      prettier: "*"
  "@xstate/tools-shared@*":
    peerDependencies:
      "@babel/core": "*"
  notistack@*:
    peerDependencies:
      csstype: "*"

yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs
